### ISSUE TITLE
Print 2D tree

### ISSUE THREAD

**Issue by SilasvanderWaal** [SilasvanderWaal/DSA_Trees#10]
Write the function that prints out a 2D visualization of the tree. The function should be implemented in the print_2d function in the ui.c file

**Comment by Alfredsson418** [comment]
Completed with latest commit, but only works up to height 5, but minimum is 4:

> Your solution need not be identical in terms of spaces,
but it must scale proportionally as the number of levels are increased and
children should be aligned underneath their parents. Your tree should dis-
play correctly up to four (4) levels to be considered correct.

**Comment by SilasvanderWaal** [comment]
At the moment the spaces do not scale, they are static. "But it must scale proportionally as the number of levels are increased" -from lab specifications

**Comment by Alfredsson418** [comment]
Should be fixed now, also scales to larges levels
